### ISSUE TITLE
How can selenium hub differentiate EdgeHTML and Chrominum-based Edge nodes

### ISSUE THREAD

**Issue by yunj** [microsoft/edge-selenium-tools#14]
Hello there, 

I currently have one node with EdgeHTML and one node with chromium-based Microsoft Edge registered against the same selenium hub. I want to run some tests ONLY on EdgeHTML node. 

My question is: how the hub can determine which node should be used due to that both nodes provide almost the same capability, i.e., browserName=MicrosoftEdge, platform=WIN10? The only difference is version. But it seems that the EdgeHTML driver doesn't allow to specify the version. 

EdgeHTML Node capability:
```
  "capabilities":
  [
    {
      "browserName": "MicrosoftEdge",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
      "version": "18.17763"
    }
  ],
```
How I create the EdgeOptions:
```
var options = new EdgeOptions();
options.BrowserVersion = "18.17763";
```

EdgeHTML Node Log:
```
[16:34:52.002] - {
  "desiredCapabilities": {
    "browserName": "MicrosoftEdge",
    "browserVersion": "18.17763"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "MicrosoftEdge",
        "browserVersion": "18.17763"
      }
    ]
  }
}

[16:34:52.017] - Response: {"value":{"error":"invalid argument","message":"The specified arguments passed to the command are invalid.","stacktrace":""}}

[16:34:52.017] - Invalid capabilities 
```

Thanks.

**Comment by bwalderman** [comment]
Hello @yunj 

The EdgeHTML driver allows you to specify the version. It only considers the major version though. Try setting "browserVersion" to just "18" for the EdgeHTML node. For example, I was able to test both EdgeHTML and Chromium using this setup:

EdgeHTML Node:

`java -jar .\selenium-server-standalone-3.141.59.jar -role node -nodeConfig edgehtml.json`

```
"capabilities": [
    {
        "browserName": "MicrosoftEdge",
        "version": "18",
        "seleniumProtocol": "WebDriver"
    }
]
```

Chromium Node:

`java -Dwebdriver.edge.driver=msedgedriver.exe -jar .\selenium-server-standalone-3.141.59.jar -role node -nodeConfig chromium.json`

```
"capabilities": [
    {
        "browserName": "MicrosoftEdge",
        "version": "83",
        "seleniumProtocol": "WebDriver"
    }
]
```

Hope this helps! Please let me know if you need any further assistance.
