### ISSUE TITLE
Does not support 83. 

### ISSUE THREAD

**Issue by potofpie** [microsoft/edge-selenium-tools#15]
It looks like I cannot run this on Edge 83 and cannot find anywhere to download old version of Chromium Edge. I like to start using this package. Does anyone have a link to where you can get old version of Chromium Edge 81.

**Comment by bwalderman** [comment]
Hello @potofpie 

It sounds like the incorrect version of msedgedriver.exe is being used. Please try downloading msedgedriver.exe version 83 from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

Hope this helps!
