### ISSUE TITLE
Python Edge driver; Cannot find MSEdge binary

### ISSUE THREAD

**Issue by spyoungtech** [microsoft/edge-selenium-tools#16]
Using the example code provided in the README, I receive the error `WebDriverException: Message: unknown error: cannot find MSEdge binary`

Edge version:  **Version 84.0.522.15 (Official build) beta (64-bit)**  (and corresponding [webdriver](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/))
Python version: **3.8**
msedge-selenium-tools==3.141.1  
selenium==3.141.0

Code to reproduce:

```python
from msedge.selenium_tools import Edge, EdgeOptions

webdriver_location = "C:\\Path\\To\\msedgedriver.exe"

options = EdgeOptions()
options.use_chromium = True
driver = Edge(options=options, executable_path=webdriver_location)
```

My only thought is perhaps that this doesn't work with the beta build?

**Comment by spyoungtech** [comment]
Fixed by adding the following

```python
options.binary_location=r'C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe'
```
:)

**Comment by duquee** [comment]
**(WSL2)** 
Hey, I feel like I recreated the error you were having but for me your fix isn't working 

`webdriver_location = '/mnt/c/WebDriver/bin/msedgedriver.exe'
options = EdgeOptions()
options.use_chromium = True
options.binary_location = '/mnt/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'`

`webdriver_location = 'C\\WebDriver\\bin\\msedgedriver.exe'
options = EdgeOptions()
options.use_chromium = True
options.binary_location = 'C\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'`

I have tried both ways and none works, and i have all of those folder in path.

**Error:**
 ´selenium.common.exceptions.WebDriverException: Message: 'C\WebDriver\bin\msedgedriver.exe' executable needs to be in PATH. Please download from http://go.microsoft.com/fwlink/?LinkId=619687´

**Comment by mchkzk** [comment]
> **(WSL2)**
> Hey, I feel like I recreated the error you were having but for me your fix isn't working
> 
> `webdriver_location = '/mnt/c/WebDriver/bin/msedgedriver.exe' options = EdgeOptions() options.use_chromium = True options.binary_location = '/mnt/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'`
> 
> `webdriver_location = 'C\\WebDriver\\bin\\msedgedriver.exe' options = EdgeOptions() options.use_chromium = True options.binary_location = 'C\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'`
> 
> I have tried both ways and none works, and i have all of those folder in path.
> 
> **Error:**
> ´selenium.common.exceptions.WebDriverException: Message: 'C\WebDriver\bin\msedgedriver.exe' executable needs to be in PATH. Please download from [http://go.microsoft.com/fwlink/?LinkId=619687´](http://go.microsoft.com/fwlink/?LinkId=619687%C2%B4)

Thank you, your variant works in Edge Can v,87.0.656.0
