### ISSUE TITLE
the file MicrosoftWebDriver.exe doenst exist

### ISSUE THREAD

**Issue by LinconEduardo** [microsoft/edge-selenium-tools#18]
when i try to run my test with this edge package i always get this error.
`\bin\Debug\MicrosoftWebDriver.exe does not exist. The driver can be downloaded at http://go.microsoft.com/fwlink/?LinkId=619687.`

i figure out, if a rename the "msedgedriver.exe" too "MicrosoftWebDriver.exe" in debug folder, the test run fine.

**Comment by bwalderman** [comment]
Hi @LinconEduardo 

The Selenium Tools package searches for the legacy driver executable (MicrosoftWebDriver.exe) by default. To use with Chromium-based Edge, create an `EdgeOptions` object with `UseChromium` set to `true`. This tells the package to search for msedgedriver.exe instead. Please check the [readme](https://github.com/microsoft/edge-selenium-tools) for details and example code in each language.
