### ISSUE TITLE
Please add java support as well for chromium Edge

### ISSUE THREAD

**Issue by harsh813** [microsoft/edge-selenium-tools#19]
Hi,
Thanks for creating this project , It really helps in running chromium edge tests with simple changes
Just wanted to know if there are any plans of adding java support as well, this will help a lot of selenium based frameworks.

**Comment by germanodulio** [comment]
Hmmm is Microsoft's github account...I don't think they will add support for java.

**Comment by bwalderman** [comment]
@harsh813, thanks for your feedback. Java support is on our roadmap. You can follow the progress of the PR here: #23

**Comment by VigneshGuhan** [comment]
@bwalderman Any ETA for this #23 will be merged to main branch for use?

**Comment by bwalderman** [comment]
@VigneshGuhan, we hope to have this available by the end of October. It will be released as a downloadable .jar and a Maven package. The code is complete, but some time is still needed to meet the signing requirements for publishing to the central Maven repository.

**Comment by VigneshGuhan** [comment]
@bwalderman  Thanks for the update 👍

**Comment by AnnaIvakhnik** [comment]
Hello @bwalderman !
Sorry for bothering :( Could you please inform us if you have any updates here about eta?

**Comment by bwalderman** [comment]
Hi @AnnaIvakhnik. I'm sorry for the delay. It is taking longer than expected to work out the mechanics of publishing this project to the central Maven repository. The ETA is now mid-December. 

Until then, you may clone and build the source code available in the [java branch](https://github.com/microsoft/edge-selenium-tools/tree/user/brwalder/java). Or, consider using Selenium 4 which already has native support for Edge Chromium and does not require this library.

**Comment by bwalderman** [comment]
Fixed with #23 

The Java bindings are now available on Maven Central and our [Releases](https://github.com/microsoft/edge-selenium-tools/releases/latest) page.
