### ISSUE TITLE
Please add strong-naming to the assembilies inside the nuget package

### ISSUE THREAD

**Issue by inthemedium** [microsoft/edge-selenium-tools#21]
Please produce strong-name signed assemblies as it makes the assemblies impossible to reference without modification by a project where strong-naming is enabled.

Selenium itself has a separate strong-named package (http://selenium-release.storage.googleapis.com/3.141/selenium-dotnet-strongnamed-3.141.0.zip). The better solution is to strong-name the assemblies and ship it in the existing package, because two packages that contain exactly the same assemblies, types, etc, could cause issues if they are in the same dependency graph.

Example of the current issue as seen in ILSpy:
`Microsoft.Edge.SeleniumTools, Version=3.141.1.0, Culture=neutral, PublicKeyToken=null`

**Comment by bwalderman** [comment]
Hi @inthemedium. We can make a separate Microsoft.Edge.SeleniumTools.StrongNamed package available for use with the official Selenium strong-named package. Our existing package depends on the official Selenium.WebDriver NuGet package which is not strong-named.

**Comment by bwalderman** [comment]
@inthemedium , the strong-named package is now available here: https://github.com/microsoft/edge-selenium-tools/releases/tag/v3.141.2

Hope this helps!
