### ISSUE TITLE
Edge Chromium Version 86.0.622.38 (Official build) (64-bit)

### ISSUE THREAD

**Issue by MatimalNAU** [microsoft/edge-selenium-tools#25]
Not working with version 86.x, will there be an update coming?

Exception: System.InvalidOperationException: 'session not created: This version of MSEdgeDriver only supports MSEdge version 84

**Comment by bwalderman** [comment]
Please update your copy of msedgedriver and ensure it matches the version of Edge installed on your machine. For more information, check out the docs at https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium
