### ISSUE TITLE
Documentation for `ms:edgeOptions`

### ISSUE THREAD

**Issue by christian-bromann** [microsoft/edge-selenium-tools#26]
Hey,

is there some sort of documentation on how `ms:edgeOptions` are structured? I assume it is similar to [chromeOptions](http://chromedriver.chromium.org/capabilities#TOC-ChromeOptions-object) but would love to see more details about what it supports and what not.

**Comment by bwalderman** [comment]
Hi @christian-bromann. That's right. EdgeOptions is similar to ChromeOptions, with some Edge-specific additions. We've just updated our documentation and the EdgeOptions docs are now live [here](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options).
