### ISSUE TITLE
How to control an opened edge with selenium

### ISSUE THREAD

**Issue by zyw727725828** [microsoft/edge-selenium-tools#33]
I tried to use the same method as chrome, but it didn't work
python thx

**Comment by bwalderman** [comment]
Can you share your code?

**Comment by zyw727725828** [comment]
> Can you share your code?

chrome_options = Options()
chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
chrome_driver = "chromedriver.exe"

driver = webdriver.Chrome(chrome_driver, chrome_options=chrome_options)


Chrome needs to set the port number --remote-debugging-port=9222

**Comment by bwalderman** [comment]
Microsoft Edge (Chromium) does not support usage with ChromeDriver. Please use EdgeDriver and EdgeOptions. For more information and code samples, visit the [readme](https://github.com/microsoft/edge-selenium-tools) and our WebDriver [docs](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium).
