### ISSUE TITLE
Update for Selenium 4.0

### ISSUE THREAD

**Issue by DeLaphante** [microsoft/edge-selenium-tools#38]
Can we have a updated version for Selenium 4 please?

I'm getting the following error

Message: 
    System.MissingMethodException : Method not found: 'OpenQA.Selenium.Remote.DesiredCapabilities OpenQA.Selenium.DriverOptions.GenerateDesiredCapabilities(Boolean)'.
    TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    EdgeOptions.ToChromiumCapabilities()
    EdgeOptions.ToCapabilities()
    EdgeDriver.ConvertOptionsToCapabilities(EdgeOptions options, Boolean serviceUsingChromium)
    EdgeDriver.ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
    EdgeDriver.ctor(EdgeOptions options)
    CallSite.Target(Closure , CallSite , Type , Object )
    UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
    Hooks.LaunchBrowser(ScenarioContext scenarioContext, FeatureContext featureContext) line 143
    TestExecutionEngine.FireEvents(HookType hookType)
    TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
    TestExecutionEngine.OnScenarioStart()
    TestExecutionEngine.OnAfterLastStep()
    TestRunner.CollectScenarioErrors()

This was working fine on Selenium 3

**Comment by bwalderman** [comment]
Hi @DeLaphante. Selenium 4 already supports Edge Chromium. It is not necessary to install "Selenium Tools for Microsoft Edge" when using Selenium 4.

To automate Edge Chromium using Selenium 4, please remove the `Microsoft.Edge.SeleniumTools` package from the project and ensure you are using Selenium 4's built-in EdgeDriver class.

**Comment by DeLaphante** [comment]
Thanks @bwalderman ...guess i wasn't aware of that
