### ISSUE TITLE
EdgeOptions is not CLS-compliant

### ISSUE THREAD

**Issue by Stefan-Ilic** [microsoft/edge-selenium-tools#4]
Hi,

I get an error when trying to use `EdgeOptions` saying that it's not CLS-compliant. I couldn't find any flags explicitly turning the compliance off, and didn't notice anything when I looked at the class myself (it is rather large, though).

Is this at all intentional? I had to use `#pragma warning disable CS3009` to derive from the class.

Best regards,
Stefan

**Comment by bwalderman** [comment]
HI @Stefan-Ilic, thanks for reporting this! We missed it unintentionally. Adding the appropriate annotations now and we'll publish a new NuGet update shortly.

**Comment by bwalderman** [comment]
@Stefan-Ilic, the fix is ready. Please update to the latest NuGet release: https://www.nuget.org/packages/Microsoft.Edge.SeleniumTools/3.141.1

**Comment by Stefan-Ilic** [comment]
Much appreciated!
