### ISSUE TITLE
How to disable SmartScreen (safebrowsing in edge) on C# Selenium Edge Chromium?

### ISSUE THREAD

**Issue by AchiraFernando** [microsoft/edge-selenium-tools#44]
I'm using Microsoft.Edge.SeleniumTools EdgeOptions to construct options for the EdgeDriver.

But the issue right now is that Edge blocks downloads.

![image](https://user-images.githubusercontent.com/15198261/115280933-166e5e00-a166-11eb-9367-e75afbc5d7e5.png)

Tried different sorts of things but none of them worked.

Same issue can be solved on Chrome by disabling "safebrowsing" on UserProfilePreferences in ChromeOptions.

I know for a fact that SmartScreen does the blocking, if that is so is there any profile preference that I can use to disable SmartScreen ?

Or any other workaround to force download without the block would be very helpful.

**Comment by miksch123** [comment]
I think this is what you might be looking for: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#smartscreenenabled

**Comment by albert-asin** [comment]
here the same problem

**Comment by Nepitwin** [comment]
I have the problem that the Smart Screen is still active in the Selenium instance.

The Smart Screen feature is globally disabled on Windows 10. However, this still blocks the downloads.
![image](https://user-images.githubusercontent.com/12249055/129542069-4a50e910-cbd2-468e-9b30-db215fbc0417.png)

What we would expect is to be able to set a configuration via the EdgeOptions to disable the SmartScreen. For Firefox and Chrome such solutions exist.

I have tried several approaches to find the right parameter but I can't find any documentation.

I found in the following issue the parameter "--disable-features=msSmartScreenProtection". Unfortunately it does not work.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/834

Is there an EdgeOptions parameter or driver argument to disable the feature from Edge?

**Comment by Nepitwin** [comment]
What i found was to disable the SmartScreenEnabled Reg key by window in HKCU and then the download is working like expected.

If the value will be set to 0. Selenium tests are working fine with edge if needed to download files.

![image](https://user-images.githubusercontent.com/12249055/129930185-7f7e5d17-ef82-49aa-8712-f123e0e08e98.png)

**Comment by bwalderman** [comment]
Hello,

Please consider upgrading to Selenium 4 if you have not done so already since this repo is now deprecated and Selenium 4 has built-in support for Microsoft Edge (Chromium). For help upgrading, see https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/#upgrading-from-selenium-3

`--disable-features=msSmartScreenProtection` is the correct way to disable SmartScreen. I've verified this with the following sample:

```csharp
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using System.Threading;

namespace EdgeDriverSample
{
    class Program
    {
        static void Main(string[] args)
        {
            var options = new EdgeOptions();
            options.AddArgument("--disable-features=msSmartScreenProtection");

            var driver = new EdgeDriver(options);

	    // Should navigate to smartscreen test site instead of blocking.
            driver.Url = "https://nav.smartscreen.msft.net/other/malware.html";

            Thread.Sleep(5000);
            driver.Quit();
        }
    }
}
```

I'm going to close this issue since this repo is now deprecated. If the download UI is not recognizing the `--disable-features=msSmartScreenProtection` parameter, you can send feedback to the Microsoft Edge team using the "Send feedback button" under "Help and feedback" in Edge's main menu.

**Comment by hailong-ph** [comment]
Hi guys, 
It seems `--disable-features=msSmartScreenProtection` doesn't work for 
Selenium 4.18.1 and Edge Version 122.0.2365.92 (Official build) (64-bit).
I'm downloading  a .xml file, and Edge blocks the download.
