### ISSUE TITLE
addcookie doesn't work with 90.0.818.46

### ISSUE THREAD

**Issue by popyoung** [microsoft/edge-selenium-tools#45]
After I updated from 89 to 90, the original code throws an exception.

OpenQA.Selenium.InvalidCookieDomainException:“invalid cookie domain: Cookie 'domain' mismatch
  (Session info: MicrosoftEdge=90.0.818.46)”

**Comment by popyoung** [comment]
The reason has been found, because of restrictions SameSite. I loaded the cookie without first navigating the corresponding domain name. It may be that SameSite has been restricted after 90 version, or the website I visited has strengthened restrictions, but it happened that I upgraded the 90 version.

**Comment by bwalderman** [comment]
@popyoung this is a known issue with the WebDriver spec. For details see https://github.com/w3c/webdriver/issues/1238 

I'm going to close this issue since this repo is now deprecated.
