### ISSUE TITLE
Msedgedriver is having issues with Capybara when executed locally [ without Grid ]

### ISSUE THREAD

**Issue by DeepakTiwari13** [microsoft/edge-selenium-tools#51]
Hi Respected Team, 

I am running my test script using msedgedriver with ruby and capybara. Below are the version information.

1. Platform : Windows 10
2. capybara (3.35.3)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
3. rspec-expectations (3.10.1)
4. selenium-webdriver (3.142.7)
5. site_prism-all_there (0.3.2)
6. ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
7. Msedgedriver version 92 [ Stable ]
8. Edge Browser version 92.0

This is how I am initializing my edge browser 

Capybara.register_driver :selenium_edge do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.edge("javascriptEnabled": true,
                                                                "cssSelectorsEnabled": true,
                                                                "takesScreenshot": true,
                                                                "nativeEvents": true,
                                                                "rotatable": true,
                                                                'ms:edgeOptions' => { 'args' => [
                                                                  "--disable-web-security"
                                                                ], w3c: false })
  Capybara::Selenium::Driver.new(app, browser: :edge,:driver_path => 'C:\Users\sum\Downloads\msedgedriver.exe',
                                 desired_capabilities: capabilities)

Observation :- 
1. Driver loads the test url.
2. NoMethodError: undefined method `gsub' for nil:NilClass
    Stacktrace : - 
    C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/capybara-3.35.3/lib/capybara/selenium/node.rb:18:in `all_text'
    C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/capybara-3.35.3/lib/capybara/node/element.rb:60:in `block in text'
    C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/capybara-3.35.3/lib/capybara/node/base.rb:83:in `synchronize'
    C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/capybara-3.35.3/lib/capybara/node/element.rb:60:in `text'

Here chrome works fine. Here code is supposed to read text from webpage. Can you please let me know if this is an issue ?

expect(@app.login_page.logo_header.text).to eq('Text') works in chromedriver
expect(@app.login_page.logo_header.text).to eq('Text') not works in edgedriver
expect(@app.login_page.logo_header.native.text).to eq('Text') works in edgedriver

If I set up the Selenium gird and I use below code ,

Capybara.register_driver :selenium_grid do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.edge
  Capybara::Selenium::Driver.new(app, browser: :remote, url: 'http://localhost:4444/wd/hub', desired_capabilities: capabilities)
end

Then edge driver works fine.

**Comment by bwalderman** [comment]
@DeepakTiwari13 Selenium 3 does not support Chromium-based Microsoft Edge. Please upgrade your tests to Selenium 4 which has proper support for the latest Microsoft Edge. You can find more info about upgrading here: https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/

I'm going to close this issue since this repo is specifically for questions about the Selenium Tools for Microsoft Edge project and not for general Edge driver or Selenium questions. We're also deprecating this repo and recommending customers upgrading to Selenium 4 instead. If you still need help after upgrading, please open a new issue in Selenium's official repo: https://github.com/SeleniumHQ/selenium/issues
