### ISSUE TITLE
Doesn't seem to work, and command line parameters don't seem to work either

### ISSUE THREAD

**Issue by NibblyPig** [microsoft/edge-selenium-tools#53]
This is my error:

> Starting MSEdgeDriver 94.0.992.38 (55a0a486d5c4c1a7374dc28a7be702fee43b3b39) on port 1307 Only local connections are allowed. Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe. MSEdgeDriver was started successfully.
> 
> DevTools listening on ws://127.0.0.1:1310/devtools/browser/c4e7f6f6-46d3-447c-b26b-3ad231a6122f [29296:584:1001/203949.853:ERROR:fallback_task_provider.cc(119)] Every renderer should have at least one task provided by a primary task provider. If a fallback task is shown, it is a bug. Please file a new bug and tag it as a dependency of crbug.com/739782. [29296:26032:1001/203954.115:ERROR:chrome_browser_main_extra_parts_metrics.cc(250)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends. [29296:584:1001/203954.143:ERROR:profile_manager.cc(1057)] Cannot create profile at path C:\Users\NibblyPig\AppData\Local\Microsoft\Edge\User Data\Default [29296:584:1001/203954.143:ERROR:profile_manager.cc(2010)] Cannot create profile at path C:\Users\NibblyPig\AppData\Local\Microsoft\Edge\User Data\Default [29296:26032:1001/203954.176:ERROR:chrome_browser_main_extra_parts_metrics.cc(254)] crbug.com/1216328: Checking default browser status ended.

From what I can ascertain from the scant information on google you need to pass an argument. There's not really any documentation on how to do this but I tried the following:

```
static void Main(string[] args)
{
    var options = new EdgeOptions();

    var capabilities = new List<string>() {
        "profile-directory=c:\\temp\\edgedriver\\temp",
        "user-data-dir=c:\\temp\\edgedriver\\temp"
    };

    options.AddAdditionalCapability("args", capabilities.ToArray());

    var driver = new EdgeDriver(@"c:\temp\edgedriver", options);

    driver.Url = "https://www.google.com";
}
```

However it doesn't seem to register the command line parameters at all, if I go to `edge://version/`

I'm just fumbling around in the dark as I see all kinds of things like references to a UseChromium flag that doesn't seem to exist, and if I don't provide the path to the executable (which incidentally has the wrong name in the zip) it gives me an exception that has a URL to get the edge driver from which is a broken link.

It may be that this entire project is just legacy/deprecated and not maintained and is broken as that's what it feels like, but if anyone knows how I can simply have a console app in .NET 4.7.2 that opens a browser and goes to google using Edge it would be appreciated.

**Comment by bwalderman** [comment]
Hi @NibblyPig 

> I'm just fumbling around in the dark as I see all kinds of things like references to a UseChromium flag that doesn't seem to exist, and if I don't provide the path to the executable (which incidentally has the wrong name in the zip) it gives me an exception that has a URL to get the edge driver from which is a broken link.

Since the `UseChromium` flag seemd to be missing and the download URL link was wrong, it sounds like you may have been using the built-in classes from Selenium 3 instead of the ones from this repo. This would also explain why command line parameters weren't working.

Now that Selenium 4 is released, I recommend upgrading your tests. Selenium 4 supports Chromium-based Microsoft Edge and all of its available options without the need for this repo. We've recently updated our documentation that should help you get started: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium
