### ISSUE TITLE
msedge-selenium-tool Python package does not exist

### ISSUE THREAD

**Issue by teetime514** [microsoft/edge-selenium-tools#7]
Readme says to do 👍 
pip install msedge-selenium-tool

But pip says package does not exist.

Python version used 3.7.6

**Comment by bwalderman** [comment]
Hi @teetime514, thanks for your interest in our project! The pip package is now live at https://pypi.org/project/msedge-selenium-tools/3.141.0/

Our readme was a little ahead of our actual release :) Sorry for the confusion.
